/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'Nish' at '12/12/15 1:29 PM' with Gradle 2.9
 *
 * @author Nish, @date 12/12/15 1:29 PM
 */

import spock.lang.Specification

class ServerTest extends Specification{

}
